### ISSUE TITLE
у меня вопрос

### ISSUE THREAD

**Issue by isinkin** [CyberBoyX/Streaks-Bot#1]
![image](https://user-images.githubusercontent.com/34765569/75036945-3a400080-54dd-11ea-912e-e2c0cafdf412.png)

ваш код основан на очередном слитом говноботе. откуда вы вообще берёте эти сурсы? почему вы не пробуете делать сами, а лепете говно на говне?

**Comment by CyberBoyX** [comment]
> ![image](https://user-images.githubusercontent.com/34765569/75036945-3a400080-54dd-11ea-912e-e2c0cafdf412.png)
> 
> ваш код основан на очередном слитом говноботе. откуда вы вообще берёте эти сурсы? почему вы не пробуете делать сами, а лепете говно на говне?

дурачок? бот был лично разработан мной за какие-то 25 минут для моей группы.. и 90% ботов которые есть..они основано на других ботах, к сожалению так бывает дружок)

**Comment by isinkin** [comment]
> > ![image](https://user-images.githubusercontent.com/34765569/75036945-3a400080-54dd-11ea-912e-e2c0cafdf412.png)
> > ваш код основан на очередном слитом говноботе. откуда вы вообще берёте эти сурсы? почему вы не пробуете делать сами, а лепете говно на говне?
> 
> дурачок? бот был лично разработан мной за какие-то 25 минут для моей группы.. и 90% ботов которые есть..они основано на других ботах, к сожалению так бывает дружок)

ты серьёзно? я этот cmd.hear во всех ТОПЛЕСЯГОРИЛЛАБОТ вижу)

**Comment by CyberBoyX** [comment]
> > > ![image](https://user-images.githubusercontent.com/34765569/75036945-3a400080-54dd-11ea-912e-e2c0cafdf412.png)
> > > ваш код основан на очередном слитом говноботе. откуда вы вообще берёте эти сурсы? почему вы не пробуете делать сами, а лепете говно на говне?
> > 
> > 
> > дурачок? бот был лично разработан мной за какие-то 25 минут для моей группы.. и 90% ботов которые есть..они основано на других ботах, к сожалению так бывает дружок)
> 
> ты серьёзно? я этот cmd.hear во всех ТОПЛЕСЯГОРИЛЛАБОТ вижу)

что дальше? ну? тебе плохо стало? да я использую некоторое как основу. И что?

**Comment by CyberBoyX** [comment]
> > > ![image](https://user-images.githubusercontent.com/34765569/75036945-3a400080-54dd-11ea-912e-e2c0cafdf412.png)
> > > ваш код основан на очередном слитом говноботе. откуда вы вообще берёте эти сурсы? почему вы не пробуете делать сами, а лепете говно на говне?
> > 
> > 
> > дурачок? бот был лично разработан мной за какие-то 25 минут для моей группы.. и 90% ботов которые есть..они основано на других ботах, к сожалению так бывает дружок)
> 
> ты серьёзно? я этот cmd.hear во всех ТОПЛЕСЯГОРИЛЛАБОТ вижу)

думаю ты меня понял
